stow -t ~ tmux
stow -t ~ gitconfig
stow -t ~ kitty
stow -t ~ gdb
stow -t ~ zsh
stow -t ~ vim
stow -t ~ bash
stow -t ~ nvim
stow -t ~ cursors
stow -t ~ hyprpaper
stow -t ~ waybar
stow -t ~ wofi
stow -t ~ hyprlock
stow -t ~ hyprland
