-- Main Hyprland config (Lua)
hl.config({ autogenerated = false })

-- Module folder is "config.d" (dotted name), which require()'s dot-to-slash
-- rule can't express, so add it to package.path and require by bare name.
package.path = os.getenv("HOME") .. "/.config/hypr/config.d/?.lua;" .. package.path

require("misc")
require("monitors")
require("environment")
require("appearance")
require("input")
require("keybinds")
require("rules")
require("autostart")
